"use client";
import {ChangeEvent,useMemo,useState} from "react";
import QRCode from "qrcode";

type Item={item_name:string;price:number|null;original_text?:string;confidence?:number};
type Category={category_name:string;items:Item[]};
type Menu={business_name:string;currency:string;categories:Category[];uncertain_fields?:string[]};
const sampleMenu:Menu={business_name:"Irani Chiya",currency:"NPR",categories:[
  {category_name:"Our Special",items:[{item_name:"Irani चिया",price:90}]},
  {category_name:"Milk Based चिया",items:[{item_name:"Kadak चिया",price:80},{item_name:"Rosemary चिया",price:70},{item_name:"Premium चिया",price:60},{item_name:"Masala चिया",price:50}]},
  {category_name:"Water Based चिया",items:[{item_name:"Black चिया",price:30},{item_name:"Lemon चिया",price:40},{item_name:"Hot Lemon",price:65},{item_name:"Hot Lemon W Honey",price:100},{item_name:"Green चिया",price:60},{item_name:"Green Tea W Honey",price:120}]},
  {category_name:"Hookas",items:[{item_name:"Regular",price:350},{item_name:"Cloud",price:495},{item_name:"Special Irani Hooka",price:845}]},
  {category_name:"Cool Sips",items:[{item_name:"Peach Ice Tea",price:150},{item_name:"Iced Tea Latte",price:125},{item_name:"Irani Special Lassi",price:125},{item_name:"Iced Lemon",price:95},{item_name:"Cherry Bliss",price:150},{item_name:"Blue Ocean",price:150},{item_name:"Pommy Red",price:165},{item_name:"Sunrise",price:180}]}
]};
const slugify=(value:string)=>value.toLowerCase().trim().replace(/[^a-z0-9\s-]/g,"").replace(/[\s-]+/g,"-").replace(/^-|-$/g,"").slice(0,60);

export default function Home(){
  const[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(""),[menu,setMenu]=useState<Menu|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(""),[model,setModel]=useState("");
  const[showPublish,setShowPublish]=useState(false),[slug,setSlug]=useState(""),[phone,setPhone]=useState(""),[whatsapp,setWhatsapp]=useState(""),[mapsUrl,setMapsUrl]=useState(""),[publishing,setPublishing]=useState(false),[publishedUrl,setPublishedUrl]=useState(""),[qr,setQr]=useState("");
  const itemCount=useMemo(()=>menu?.categories.reduce((s,c)=>s+c.items.length,0)??0,[menu]);
  function chooseFile(e:ChangeEvent<HTMLInputElement>){const next=e.target.files?.[0]??null;setFile(next);setMenu(null);setError("");setModel("");setPublishedUrl("");if(preview)URL.revokeObjectURL(preview);setPreview(next?URL.createObjectURL(next):"")}
  async function extract(){if(!file)return;if(file.size>8*1024*1024){setError("Please upload an image smaller than 8 MB.");return}setLoading(true);setError("");try{const dataUrl=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=reject;r.readAsDataURL(file)});const res=await fetch("/api/extract",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({dataUrl})});const data=await res.json();if(!res.ok)throw new Error(data.error||"We could not read this menu.");setMenu(data.menu);setModel(data.model);setSlug(slugify(data.menu.business_name))}catch(e){setError(e instanceof Error?e.message:"We could not read this menu.")}finally{setLoading(false)}}
  function updateItem(ci:number,ii:number,field:"item_name"|"price",value:string){if(!menu)return;const next=structuredClone(menu),item=next.categories[ci].items[ii];if(field==="price")item.price=value===""?null:Number(value);else item.item_name=value;setMenu(next)}
  function openPublish(){if(!menu)return;setSlug(slug||slugify(menu.business_name));setShowPublish(true);setError("")}
  async function publish(){if(!menu)return;setPublishing(true);setError("");try{const res=await fetch("/api/publish",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({menu,slug,phone,whatsapp,mapsUrl})}),data=await res.json();if(!res.ok)throw new Error(data.error||"Could not publish menu.");const url=`${window.location.origin}${data.path}`;setPublishedUrl(url);setQr(await QRCode.toDataURL(url,{width:900,margin:2,color:{dark:"#14231d",light:"#ffffff"},errorCorrectionLevel:"H"}))}catch(e){setError(e instanceof Error?e.message:"Could not publish menu.")}finally{setPublishing(false)}}
  function downloadQr(){const a=document.createElement("a");a.href=qr;a.download=`${slug}-menu-qr.png`;a.click()}
  return <main>
    <header className="topbar"><a className="brand" href="#"><span className="brandMark">म</span>MenuSathi</a><span className="badge">Nepal-first menu digitizer</span></header>
    <section className="intro"><div><p className="eyebrow">PHOTO TO LIVE QR MENU</p><h1>Turn any paper menu into a live QR menu.</h1><p className="lede">Upload a photo. AI reads every category, item and price. You verify it, then publish a mobile menu customers can scan.</p></div><div className="trust"><span>✓ NPR-aware</span><span>✓ नेपाली + English</span><span>✓ Owner verified</span></div></section>
    <section className="workspace"><div className="panel uploadPanel"><div className="step"><span>01</span><div><h2>Upload your menu</h2><p>A straight, well-lit photo gives the best result.</p></div></div>
      <label className={`dropzone ${preview?"hasImage":""}`}>{preview?<img src={preview} alt="Selected menu"/>:<><span className="uploadIcon">↑</span><strong>Choose a menu photo</strong><small>JPG, PNG or WEBP · up to 8 MB</small></>}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={chooseFile}/></label>
      <button className="primary" disabled={!file||loading} onClick={extract}>{loading?"Reading items and prices…":"Extract menu"}<span>→</span></button><button className="sample" onClick={()=>{setMenu(sampleMenu);setModel("Benchmark example");setSlug("irani-chiya")}}>View benchmark result</button>{error&&!showPublish&&<div className="error">{error}</div>}<div className="modelChain"><span>Automatic fallback</span><ol><li>Gemini Flash</li><li>Gemini Preview</li><li>Gemini fallback</li></ol></div></div>
      <div className="panel resultPanel"><div className="step"><span>02</span><div><h2>Verify the extraction</h2><p>Correct names or prices before publishing.</p></div></div>
      {!menu?<div className="empty"><div className="emptyMenu"><i></i><i></i><i></i></div><strong>Your extracted menu appears here</strong><p>Nothing is published automatically.</p></div>:<><div className="summary"><div><label>Business</label><input value={menu.business_name} onChange={e=>{setMenu({...menu,business_name:e.target.value});setSlug(slugify(e.target.value))}}/></div><div><label>Currency</label><input value={menu.currency} onChange={e=>setMenu({...menu,currency:e.target.value})}/></div><div className="count"><strong>{itemCount}</strong><span>items found</span></div></div><div className="detected">Extracted with {model}</div><div className="categories">{menu.categories.map((c,ci)=><section key={ci} className="category"><input className="categoryName" value={c.category_name} onChange={e=>{const n=structuredClone(menu);n.categories[ci].category_name=e.target.value;setMenu(n)}}/>{c.items.map((item,ii)=><div className="menuRow" key={ii}><input value={item.item_name} onChange={e=>updateItem(ci,ii,"item_name",e.target.value)}/><div className="price"><span>Rs</span><input type="number" value={item.price??""} onChange={e=>updateItem(ci,ii,"price",e.target.value)}/></div></div>)}</section>)}</div><button className="publish" onClick={openPublish}>Publish QR Menu <span>03 →</span></button></>}</div></section>
    {showPublish&&menu&&<div className="modalBackdrop"><section className="publishModal" role="dialog" aria-modal="true" aria-labelledby="publish-title"><button className="close" onClick={()=>setShowPublish(false)} aria-label="Close">×</button>{!publishedUrl?<><p className="eyebrow">FINAL STEP</p><h2 id="publish-title">Publish {menu.business_name}</h2><p className="modalLead">Add customer contact options. All are optional.</p><label>Public link<div className="slugInput"><span>{typeof window!=="undefined"?window.location.host:"menusathi.com"}/</span><input value={slug} onChange={e=>setSlug(slugify(e.target.value))}/></div></label><div className="fieldGrid"><label>Call number<input placeholder="9800000000" value={phone} onChange={e=>setPhone(e.target.value)}/></label><label>WhatsApp number<input placeholder="9779800000000" value={whatsapp} onChange={e=>setWhatsapp(e.target.value)}/></label></div><label>Google Maps share link<input placeholder="https://maps.app.goo.gl/..." value={mapsUrl} onChange={e=>setMapsUrl(e.target.value)}/></label>{error&&<div className="error">{error}</div>}<button className="primary publishNow" disabled={publishing||slug.length<3} onClick={publish}>{publishing?"Publishing…":"Publish menu & create QR"}<span>→</span></button></>:<div className="success"><span className="successIcon">✓</span><p className="eyebrow">MENU IS LIVE</p><h2 id="publish-title">Ready for customers</h2><a className="liveLink" href={publishedUrl} target="_blank" rel="noreferrer">{publishedUrl}</a><img src={qr} alt={`QR code for ${menu.business_name} menu`}/><div className="successActions"><button onClick={downloadQr}>Download printable QR</button><a href={publishedUrl} target="_blank" rel="noreferrer">Open customer menu</a></div><p className="printHint">Print the QR and place it on tables, the counter, or your wall.</p></div>}</section></div>}
    <footer><span>Built for Nepal’s cafés, chiya hubs and restaurants.</span><span>Private until you press Publish QR Menu.</span></footer>
  </main>
}
